vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: assets/img/posts_images
            upload_destination: '%kernel.project_dir%/public/assets/img/posts_images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
