vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: assets/img/posting_image
            upload_destination: '%kernel.project_dir%/public/assets/img/posting_image'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
