# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: jakzal/phpqa:php8.1
before_script:
  - composer install --no-scripts
cache:
  paths:
    - vendor/
stages:
  - CodingStandards
  - UnitTests
phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_failure: false
phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false
twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false
phpunit:
  stage: UnitTests
  script:
    - php bin/phpunit
  allow_failure: false