version: '3.8'

services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
        POSTGRES_USER: tattoo
        POSTGRES_PASSWORD: tattoo
        PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - type: volume
        source: dbtest
        target: /var/lib/postgresql/data/pgdata
    ports:
      - 8080:5432

  php:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://tattoo:tattoo@postgres:5432/tattoo?serverVersion=13&charset=utf8
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy$$
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  php_socket:
  ###> doctrine/doctrine-bundle ###
  dbtest:
###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###